### ISSUE TITLE
《CTnoCVR: A Novelty Auxiliary Task Making the Lower-CTR-Higher-CVR Upper》论文的源代码啥时候开源呐？

### ISSUE THREAD

**Issue by rogeroyer** [scalaboy/MutiTaskLearning#1]

**Comment by scalaboy** [comment]
https://github.com/scalaboy/MutiTaskLearn
 code is  here

**Comment by scalaboy** [comment]
> _No description provided._

https://github.com/scalaboy/MutiTaskLearn
code is here
